const API_URL = process.env.REACT_APP_API_HOST;
const SOL_WALLET = process.env.REACT_APP_SOL_ADDRESS;
const SOL_NETWORK = process.env.REACT_APP_SOL_NETWORK;
const COMMING_SOON = process.env.REACT_APP_MODE_COMMING_SOON;

export { API_URL, SOL_WALLET, SOL_NETWORK, COMMING_SOON };
